project:
  type: website

website:
  title: "Andrei Akimov - Earthquake Seismology"
  site-url: "https://akimov-seismology.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Research Notes
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/akimov-seismology

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
